### PR TITLE
Upgrade to 2.3.2

### PR DESCRIPTION
**Pull request by saraedum**

### CODE REVIEW

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender

**Comment by saraedum** [comment]
It's now failing with the following:
```
In file included from ../../../fflas-ffpack/fflas/fflas_simd.h:208:0,
                 from ../../../fflas-ffpack/fflas/fflas_freduce.h:33,
                 from ../../../fflas-ffpack/fflas/fflas.h:104,
                 from fflas_L1_inst.C:34:
../../../fflas-ffpack/fflas/fflas_simd/simd256.inl: In static member function ‘static Simd256i_base::vect_t Simd256i_base::sll128(Simd256i_base::vect_t)’:
../../../fflas-ffpack/fflas/fflas_simd/simd256.inl:102:85: error: there are no arguments to ‘_mm256_bslli_epi128’ that depend on a template parameter, so a declaration of ‘_mm256_bslli_epi128’ must be available [-fpermissive]
```
The same problem seemed to happen here https://groups.google.com/forum/#!topic/sage-support/2WwdCMxZyrQ.

**Comment by saraedum** [comment]
We had `./configure --disable-simd` but it does not seem to exist anymore.

**Comment by saraedum** [comment]
On OSX, `-arch` and its argument are strangely separated:
```
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I../../.. -I../../.. -I/Users/travis/miniconda3/conda-bld/fflas-ffpack_1523409514933/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include -I/Users/travis/miniconda3/conda-bld/fflas-ffpack_1523409514933/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include -O2 -Wall -g -I/Users/travis/miniconda3/conda-bld/fflas-ffpack_1523409514933/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include -O2 -arch -fPIC -g -m64 -mmacosx-version-min=10.9 -msse -msse2 -std=gnu++11 -stdlib=libc++ x86_64 -MT fflas_L2_inst.lo -MD -MP -MF .deps/fflas_L2_inst.Tpo -c fflas_L2_inst.C  -fno-common -DPIC -o .libs/fflas_L2_inst.o
clang: clang: error: error: no such file or directory: 'x86_64'no such file or directory: 'x86_64'
```

**Comment by saraedum** [comment]
Waiting for https://github.com/conda-forge/givaro-feedstock/pull/4 before we can continue here.

**Comment by saraedum** [comment]
@isuruf Thanks for figuring that one out.

**Comment by saraedum** [comment]
Nothing, it leaves the arguments alone. I guess deleting that line would have been better.
Anyway, now I need aclocal-1.15. How do you do this usually? Add a patch with the modified configure? Or include aclocal?

**Comment by isuruf** [comment]
Include aclocal is easier to maintain. `automake` package has `aclocal` in it

**Pull request merged**
